### PR TITLE
Set up AWS S3

### PR DESCRIPTION
**Pull request by vicscherman**
/utils/uploadFiles.js
-validates file type, pushes to aws, returns key value pair

routes/uploadImg.js creates route for images upload

### What this PR does (required):
Setting up framework for pushing files to AWS S3 and generating image key and URL

### Screenshots / Videos (required):
I tested it on a separate playground build with a basic front end .would love to test with team

### Any information needed to test this feature (required):
-waiting on front end to show flow through app. Requires AWS login credentials. I have those stored in my local .env file, not able to push that to GitHub without Amazon shutting down access credentials

### Any issues with the current functionality (optional):
- List any problems where you were not able to complete all tasks on ticket
- List any problems this PR may cause for the project or other active PRs
- Post a screenshot/video of the problem, along with detailed console outputs where applicable

### CODE REVIEW

**Review by dproc96 — COMMENTED** [review]
Did this task include setting up an upload route? At the moment I can't really test the logic but it looks correct.

Also just a note, it's good to break your changes up into more than 1 commit as you can isolate specific changes.

**Comment by vicscherman** [comment]
Had to reconfigure certain things to work (consolidated helper function into route) Added an imgupload route to the app.js as well

**Comment by vicscherman** [comment]
Alright all done and working! Please give go ahead to merge and I'll pick up a new task.

**Review by bonnieli — APPROVED** [review]
Just to be clear you don't need to do one task one after the other, you can do them all in parallel even if you're waiting for an approval!

**Pull request merged**
